apiVersion: v1
kind: Secret
metadata:
  name: weather-secret
type: Opaque
data:
  # weather_pass  (base64 encoded)
  DB_PASS: d2VhdGhlcl9wYXNz
  # weather_user  (base64 encoded)
  POSTGRES_USER: d2VhdGhlcl91c2Vy
  # weather_pass  (base64 encoded)
  POSTGRES_PASSWORD: d2VhdGhlcl9wYXNz
